apiVersion: v1
kind: Service
metadata:
  name: spoolman
  namespace: namespace-workflow-1760116188180
  labels:
    app.kubernetes.io/name: spoolman
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: spoolman
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000